### PR TITLE
Single Page Application (SPA) concept add to project with Date and time

### PR DESCRIPTION
**Pull request by Hidar37**
- Contact page added to project completely.
- Style add to contact page.
- SPA conapt add to project.
- Navigation add to project.
- Style add to Navigation.
- Date and Time add to Project.
- Style add to Date and Time section.
- Linter error remove from the project.
- Readme File updated completely.

### CODE REVIEW

**Comment by Gopxfs** [comment]
As displayed below:
https://github.com/microverseinc/curriculum-javascript/blob/main/books/images/awesome_books_full_website.png

Please make sure to follow the Contact section wireframe 😉.

Your section:

**Review by Gopxfs — CHANGES_REQUESTED** [review]
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi team👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights :rocket:
✔️ No linter errors.
✔️ Great code structure. Well done!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gopxfs** [comment]
https://github.com/c00p75/Awesome-books/blob/feature/index.html#L46

Kindly notice that the corresponding path for your JS script isn't working. I tried this one and it worked 😉:
image

**Comment by Gopxfs** [comment]
Well done creating a SPA! Although, kindly notice that the Add New & Contact section are overlapping, when clicking in this order.
Add New:
image

Add New after clicking on Contact:
image

**Comment by Gopxfs** [comment]
As displayed below:
https://github.com/microverseinc/curriculum-javascript/blob/main/books/images/awesome_books_full_website.png

Please make sure to follow the Contact section wireframe 😉.

Your section:
image

**Review by FrederickMih — APPROVED** [review]
## Hi :raising_hand:  @Hidar37 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights :green_circle: 

- Descriptive PR :heavy_check_mark: 
- Linters checks are passing :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
